spring.application.name=udaw-eats

spring.jpa.hibernate.ddl-auto=update
# Database connection settings
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql=true

# Hibernate specific settings for MySQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.id.new_generator_mappings=true
spring.jpa.properties.hibernate.format_sql=true

# MySQL specific settings
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.maximum-pool-size=5

# Stripe API key from environment variable
stripe.api.key=${STRIPE_API_KEY}

# Frontend base URL for redirects
frontend.base.url=${FRONTEND_BASE_URL:http://localhost}